"""
Claude Code Integration Module
Integrates with Claude Code for AI-powered reasoning and decision making
"""

import subprocess
import json
import time
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional


class ClaudeCodeIntegration:
    """
    Integration with Claude Code for AI-powered reasoning.
    
    This module:
    - Sends tasks to Claude Code for analysis
    - Receives reasoning and plans from Claude
    - Executes Claude's recommendations via MCP servers
    - Tracks progress and completion
    """

    def __init__(self, vault_path: str, reasoning_module=None):
        """
        Initialize Claude Code integration.
        
        Args:
            vault_path: Path to the Obsidian vault
            reasoning_module: Optional reasoning module instance
        """
        self.vault_path = Path(vault_path)
        self.reasoning_module = reasoning_module
        
        # Claude Code configuration
        self.claude_command = "claude"  # Claude Code CLI command
        self.timeout = 300  # 5 minutes timeout for Claude responses
        
        # Company handbook path for context
        self.handbook_path = Path(__file__).parent / "Company_Handbook.md"
        
    def analyze_with_claude(self, task_analysis: Dict[str, Any]) -> Dict[str, Any]:
        """
        Send task analysis to Claude Code for reasoning.
        
        Args:
            task_analysis: Task analysis from reasoning module
            
        Returns:
            Claude's analysis and recommendations
        """
        # Build the prompt for Claude
        prompt = self._build_claude_prompt(task_analysis)
        
        try:
            # Call Claude Code CLI
            result = self._call_claude_code(prompt)
            
            if result.get("success"):
                claude_response = result.get("response", "")
                
                # Parse Claude's recommendations
                recommendations = self._parse_claude_response(claude_response)
                
                return {
                    "success": True,
                    "claude_analysis": recommendations,
                    "raw_response": claude_response,
                    "analyzed_at": datetime.now().isoformat()
                }
            else:
                return {
                    "success": False,
                    "error": result.get("error", "Claude Code call failed"),
                    "fallback": self._generate_fallback_plan(task_analysis)
                }
                
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "fallback": self._generate_fallback_plan(task_analysis)
            }
    
    def execute_claude_plan(self, plan: Dict[str, Any], 
                           skill_executor=None) -> Dict[str, Any]:
        """
        Execute the plan generated by Claude.
        
        Args:
            plan: Plan dictionary with steps to execute
            skill_executor: Function to execute skills
            
        Returns:
            Execution results
        """
        results = {
            "success": True,
            "steps_executed": [],
            "errors": []
        }
        
        steps = plan.get("steps", [])
        
        for i, step in enumerate(steps, 1):
            step_name = step.get("name", f"Step {i}")
            step_action = step.get("action")
            step_params = step.get("parameters", {})
            
            # Execute the step
            if skill_executor and step_action:
                try:
                    step_result = skill_executor(step_action, step_params)
                    
                    results["steps_executed"].append({
                        "step": step_name,
                        "action": step_action,
                        "result": step_result,
                        "executed_at": datetime.now().isoformat()
                    })
                    
                    if not step_result.get("success"):
                        results["errors"].append({
                            "step": step_name,
                            "error": step_result.get("error")
                        })
                        
                except Exception as e:
                    results["errors"].append({
                        "step": step_name,
                        "error": str(e)
                    })
            else:
                # Log step without execution
                results["steps_executed"].append({
                    "step": step_name,
                    "action": step_action,
                    "result": {"skipped": True},
                    "executed_at": datetime.now().isoformat()
                })
        
        return results
    
    def run_reasoning_loop(self, task_file: Path, 
                          skill_executor=None) -> Dict[str, Any]:
        """
        Run the complete reasoning loop for a task.
        
        Args:
            task_file: Path to the task file
            skill_executor: Function to execute skills
            
        Returns:
            Complete loop results
        """
        loop_results = {
            "task_file": str(task_file),
            "success": False,
            "stages": {}
        }
        
        # Stage 1: Analyze task
        loop_results["stages"]["analysis"] = self.reasoning_module.analyze_task(task_file)
        
        if not loop_results["stages"]["analysis"].get("success"):
            loop_results["error"] = "Task analysis failed"
            return loop_results
        
        analysis = loop_results["stages"]["analysis"]
        
        # Stage 2: Create plan
        loop_results["stages"]["plan_creation"] = self.reasoning_module.create_plan(analysis)
        
        if not loop_results["stages"]["plan_creation"].get("success"):
            loop_results["error"] = "Plan creation failed"
            return loop_results
        
        plan_result = loop_results["stages"]["plan_creation"]
        task_name = analysis.get("task_name", "unknown")
        
        # Stage 3: Get Claude's input (if available)
        claude_result = self.analyze_with_claude(analysis)
        loop_results["stages"]["claude_analysis"] = claude_result
        
        # Stage 4: Execute plan steps
        execution_results = self.execute_claude_plan(
            claude_result.get("claude_analysis", {}),
            skill_executor
        )
        loop_results["stages"]["execution"] = execution_results
        
        # Stage 5: Update progress for each step
        for step_result in execution_results.get("steps_executed", []):
            progress_result = self.reasoning_module.update_plan_progress(
                task_name,
                step_result.get("step"),
                step_result.get("result")
            )
            
        # Stage 6: Check completion
        loop_results["stages"]["completion_check"] = self.reasoning_module.check_completion(task_name)
        
        # Overall success
        loop_results["success"] = loop_results["stages"]["completion_check"].get("complete", False)
        loop_results["completed_at"] = datetime.now().isoformat()
        
        return loop_results
    
    def _build_claude_prompt(self, task_analysis: Dict[str, Any]) -> str:
        """Build the prompt to send to Claude Code"""
        task_name = task_analysis.get("task_name", "Unknown Task")
        task_type = task_analysis.get("task_type", "general")
        complexity = task_analysis.get("complexity", "unknown")
        content_preview = task_analysis.get("content_preview", "")
        suggested_actions = task_analysis.get("suggested_actions", [])
        requires_approval = task_analysis.get("requires_approval", False)
        
        # Load company handbook for context
        handbook_content = ""
        if self.handbook_path.exists():
            handbook_content = self.handbook_path.read_text(encoding='utf-8')[:2000]
        
        prompt = f"""You are the reasoning engine for an AI Personal Employee system.

## Task to Analyze

**Task Name:** {task_name}
**Type:** {task_type}
**Complexity:** {complexity}
**Requires Approval:** {"Yes" if requires_approval else "No"}

## Task Content

{content_preview}

## Suggested Actions

{chr(10).join(f"- {action}" for action in suggested_actions)}

## Company Handbook Rules

{handbook_content}

## Your Task

Please analyze this task and provide:

1. **Understanding**: Brief summary of what needs to be done
2. **Decision**: What action should be taken based on company rules
3. **Steps**: Ordered list of specific actions to execute
4. **Approval Check**: Whether human approval is required
5. **Risks**: Any potential issues to watch for

## Response Format

Respond in this JSON format:
```json
{{
    "understanding": "Brief summary",
    "decision": "What action to take",
    "steps": [
        {{"name": "Step 1", "action": "skill_name", "parameters": {{}}}},
        {{"name": "Step 2", "action": "skill_name", "parameters": {{}}}}
    ],
    "requires_approval": true/false,
    "risks": ["risk1", "risk2"]
}}
```

Provide your analysis:"""

        return prompt
    
    def _call_claude_code(self, prompt: str) -> Dict[str, Any]:
        """
        Call Claude Code CLI with the prompt.
        
        Args:
            prompt: Prompt to send to Claude
            
        Returns:
            Claude's response
        """
        try:
            # Try to call Claude Code CLI
            # Note: This assumes Claude Code is installed and in PATH
            process = subprocess.Popen(
                [self.claude_command, "--prompt", prompt],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
            
            stdout, stderr = process.communicate(timeout=self.timeout)
            
            if process.returncode == 0:
                return {
                    "success": True,
                    "response": stdout
                }
            else:
                return {
                    "success": False,
                    "error": f"Claude Code returned code {process.returncode}: {stderr}"
                }
                
        except subprocess.TimeoutExpired:
            process.kill()
            return {
                "success": False,
                "error": f"Claude Code timed out after {self.timeout} seconds"
            }
        except FileNotFoundError:
            # Claude Code CLI not found - use fallback
            return {
                "success": False,
                "error": "Claude Code CLI not found. Using fallback reasoning.",
                "use_fallback": True
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
    
    def _parse_claude_response(self, response: str) -> Dict[str, Any]:
        """
        Parse Claude's response to extract structured data.
        
        Args:
            response: Claude's text response
            
        Returns:
            Parsed structured data
        """
        # Try to find JSON in the response
        import re
        
        # Look for JSON code block
        json_match = re.search(r'```json\s*(.*?)\s*```', response, re.DOTALL)
        
        if json_match:
            json_str = json_match.group(1)
            try:
                return json.loads(json_str)
            except json.JSONDecodeError:
                pass
        
        # Try to parse raw JSON if no code block
        try:
            # Find first { and last }
            start = response.find('{')
            end = response.rfind('}') + 1
            if start >= 0 and end > start:
                json_str = response[start:end]
                return json.loads(json_str)
        except json.JSONDecodeError:
            pass
        
        # Fallback: return unstructured response
        return {
            "understanding": response[:500],
            "steps": [],
            "requires_approval": False,
            "raw_response": response
        }
    
    def _generate_fallback_plan(self, task_analysis: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate a fallback plan when Claude is unavailable.
        
        Args:
            task_analysis: Task analysis dictionary
            
        Returns:
            Fallback plan
        """
        suggested_actions = task_analysis.get("suggested_actions", [])
        requires_approval = task_analysis.get("requires_approval", False)
        
        steps = []
        for i, action in enumerate(suggested_actions, 1):
            # Map action descriptions to skill names
            action_lower = action.lower()
            
            if 'email' in action_lower and ('send' in action_lower or 'response' in action_lower):
                steps.append({
                    "name": f"Step {i}: {action}",
                    "action": "email_mcp_action",
                    "parameters": {"action": "create_draft" if requires_approval else "send"}
                })
            elif 'linkedin' in action_lower or 'post' in action_lower:
                steps.append({
                    "name": f"Step {i}: {action}",
                    "action": "linkedin_mcp_action",
                    "parameters": {"action": "create_draft" if requires_approval else "create_post"}
                })
            elif 'file' in action_lower or 'move' in action_lower:
                steps.append({
                    "name": f"Step {i}: {action}",
                    "action": "filesystem_mcp_action",
                    "parameters": {"action": "move_file"}
                })
            else:
                steps.append({
                    "name": f"Step {i}: {action}",
                    "action": None,
                    "parameters": {}
                })
        
        return {
            "understanding": task_analysis.get("content_preview", "")[:200],
            "decision": "Execute suggested actions using available MCP servers",
            "steps": steps,
            "requires_approval": requires_approval,
            "risks": ["Fallback mode - manual review recommended"],
            "fallback_mode": True
        }


def get_claude_integration(vault_path: str, 
                           reasoning_module=None) -> ClaudeCodeIntegration:
    """
    Factory function to get a Claude integration instance.
    
    Args:
        vault_path: Path to the Obsidian vault
        reasoning_module: Optional reasoning module instance
        
    Returns:
        ClaudeCodeIntegration instance
    """
    return ClaudeCodeIntegration(vault_path, reasoning_module)
